environment:
	matrix:
		- nodejs_version: "0.12.7"
		- nodejs_version: "4.1.2"

install:
	- ps: Install-Product node $env:nodejs_version
	- npm install

test_script:
	- node --version
	- npm --version
	- npm run test:single

build: off
